apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: classpod01
  name: classpod01
spec:
  containers:
  - image: nginx
    name: classpod01
    resources: 
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
