---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: secret
spec: {}
---
status: {}
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bb
  name: bb
  namespace: secret
spec:
  containers:
  - args:
    - "sleep"
    - "3600"
    image: busybox
    name: bb
    resources: 
      requests:
        memory: "64Mi"
      limits:
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
status: {}
