---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: ns01
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: practice
    run: nginx
  name: nginx
  namespace: ns01
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
