apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mydb
  name: mydb
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    image: mariadb
    name: mydb
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
