apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod01
  name: pod01
spec:
  containers:
  - image: nginx
    name: pod01
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
